//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCG_Portal.Models.BCGModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bcvitbg_EntityEntities : DbContext
    {
        public bcvitbg_EntityEntities()
            : base("name=bcvitbg_EntityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCompleteOrder> tblCompleteOrders { get; set; }
        public virtual DbSet<tblContext> tblContexts { get; set; }
        public virtual DbSet<tblCurrency> tblCurrencies { get; set; }
        public virtual DbSet<tblCustomerReview> tblCustomerReviews { get; set; }
        public virtual DbSet<tblDiscount> tblDiscounts { get; set; }
        public virtual DbSet<tblIPLoginAttempt> tblIPLoginAttempts { get; set; }
        public virtual DbSet<tblLanguage> tblLanguages { get; set; }
        public virtual DbSet<tblOrder> tblOrders { get; set; }
        public virtual DbSet<tblOrderStatus> tblOrderStatuses { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblProfilePicturesAdmin> tblProfilePicturesAdmins { get; set; }
        public virtual DbSet<tblProfilePicturesShopper> tblProfilePicturesShoppers { get; set; }
        public virtual DbSet<tblQuantity> tblQuantities { get; set; }
        public virtual DbSet<tblResource> tblResources { get; set; }
        public virtual DbSet<tblShopingCart> tblShopingCarts { get; set; }
        public virtual DbSet<tblShopperGroup> tblShopperGroups { get; set; }
        public virtual DbSet<tblShopper> tblShoppers { get; set; }
        public virtual DbSet<tblStaticResource> tblStaticResources { get; set; }
        public virtual DbSet<tblStaticText> tblStaticTexts { get; set; }
    }
}
