//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCG_Portal.Models.BCGModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiscount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDiscount()
        {
            this.tblProducts = new HashSet<tblProduct>();
            this.tblShoppers = new HashSet<tblShopper>();
        }
    
        public int IdDiscount { get; set; }
        public int DiscountAmount { get; set; }
        public Nullable<System.DateTime> StartDateOfDiscount { get; set; }
        public Nullable<System.DateTime> EndDateOfDiscount { get; set; }
        public string DiscountKey { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct> tblProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblShopper> tblShoppers { get; set; }
    }
}
