//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCG_Portal.Models.BCGModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public int IdOrder { get; set; }
        public int IdOrders { get; set; }
        public int IdProduct { get; set; }
        public int IdOrderStatus { get; set; }
        public int IdQuantity { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int QuantityLeft { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual tblCompleteOrder tblCompleteOrder { get; set; }
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblQuantity tblQuantity { get; set; }
        public virtual tblOrderStatus tblOrderStatus { get; set; }
    }
}
