//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCG_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProfilePicturesShopper
    {
        public int IdProfilePicture { get; set; }
        public int IdShopper { get; set; }
        public string PicturePath { get; set; }
        public bool IsProfile { get; set; }
        public bool IsVisible { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual tblShopper tblShopper { get; set; }
    }
}
