//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCG_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShopper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblShopper()
        {
            this.tblCompleteOrders = new HashSet<tblCompleteOrder>();
            this.tblCustomerReviews = new HashSet<tblCustomerReview>();
            this.tblProfilePicturesShoppers = new HashSet<tblProfilePicturesShopper>();
            this.tblShopingCarts = new HashSet<tblShopingCart>();
        }
    
        public int IdShopper { get; set; }
        public Nullable<int> IdShopperGroup { get; set; }
        public Nullable<int> IdDiscount { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> MobilePhone { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Country { get; set; }
        public string CompanyName { get; set; }
        public Nullable<bool> IsMessageForDiscountSended { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ConfirmationToken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompleteOrder> tblCompleteOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerReview> tblCustomerReviews { get; set; }
        public virtual tblDiscount tblDiscount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProfilePicturesShopper> tblProfilePicturesShoppers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblShopingCart> tblShopingCarts { get; set; }
        public virtual tblShopperGroup tblShopperGroup { get; set; }
    }
}
