//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCG_Portal.Models.BCGDB_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLanguage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLanguage()
        {
            this.tblResources = new HashSet<tblResource>();
            this.tblStaticResources = new HashSet<tblStaticResource>();
        }
    
        public int IdLanguage { get; set; }
        public string Language { get; set; }
        public string Initials { get; set; }
        public string Culture { get; set; }
        public byte[] Picture { get; set; }
        public bool IsActive { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> Datechanged { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblResource> tblResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStaticResource> tblStaticResources { get; set; }
    }
}
