//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCG_Portal.Models.BCGDB_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShopingCart
    {
        public int IdShopingCart { get; set; }
        public int IdShopper { get; set; }
        public int IdProduct { get; set; }
        public int IdQuantity { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblQuantity tblQuantity { get; set; }
        public virtual tblShopper tblShopper { get; set; }
    }
}
